apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-falcosidekick
  namespace: log-stack
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: falcosidekick-0.5.4
    app.kubernetes.io/instance: falco
    app.kubernetes.io/managed-by: Helm